name: centabit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter_svg: ^2.2.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_form_builder: ^10.2.0
  freezed_annotation: ^3.1.0
  form_builder_validators: ^11.0.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  shared_preferences: ^2.5.4
  google_fonts: ^6.3.3
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  cupertino_calendar_picker: ^2.2.6
  gradient_borders: ^1.0.2
  toastification: ^3.0.3
  fl_chart: ^1.1.0
  intl: ^0.20.2
  google_nav_bar: ^5.0.7
  flutter_sticky_header: ^0.8.0
  sticky_grouped_list: ^3.1.0
  drift: ^2.19.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.4
  path: ^1.9.0
  google_sign_in: ^6.2.2
  talker_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  drift_dev: ^2.19.0

flutter:
  uses-material-design: true

  assets: 
    - .env.dev
    - assets/images/logo.dark.svg
    - assets/images/logo.light.svg

  fonts:
    - family: TablerIcons
      fonts:
        - asset: assets/fonts/TablerIcons.ttf
